spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.pool-name=SupabaseHikariPool
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect    

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.tkdoon.ticket_app.entity
mybatis.configuration.map-underscore-to-camel-case=true
server.port=${PORT:8080}
server.servlet.session.cookie.same-site=Strict
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

logging.level.com.tkdoon.ticket_app=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

google.client-id=763067596203-8mrn7tqm5lg89ns6vhjn48epg9cjcv94.apps.googleusercontent.com
google.redirect-uri=http://localhost:8080/auth/callback/google
app.frontend-url=http://localhost:3000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true