spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.pool-name=SupabaseHikariPool
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect    

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.tkdoon.ticket_app.entity
mybatis.configuration.map-underscore-to-camel-case=true
server.port=${PORT:8080}